namespace NiORM.Attributes
{
    /// <summary>
    /// Attribute to mark a property as a primary key in the database table
    /// </summary>
    /// <remarks>
    /// This attribute is used to identify properties that serve as primary keys in the database.
    /// It supports both auto-incremental integer keys and GUID-based keys.
    /// Multiple properties can be marked as primary keys for composite keys.
    /// </remarks>
    /// <example>
    /// <code>
    /// public class User : ITable
    /// {
    ///     [PrimaryKey(isAutoIncremental: true)]
    ///     public int Id { get; set; }
    ///     
    ///     // Or for GUID primary key:
    ///     [PrimaryKey(isAutoIncremental: true, isGUID: true)]
    ///     public string UserId { get; set; }
    /// }
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    public class PrimaryKey : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the PrimaryKey attribute with default settings
        /// </summary>
        /// <remarks>
        /// Default: IsAutoIncremental = true, IsGUID = false
        /// </remarks>
        public PrimaryKey() { }

        /// <summary>
        /// Initializes a new instance of the PrimaryKey attribute with specified settings
        /// </summary>
        /// <param name="isAutoIncremental">Indicates whether the primary key is auto-incremental. Default is true.</param>
        /// <param name="isGUID">Indicates whether the primary key is a GUID. Default is false.</param>
        /// <remarks>
        /// When isGUID is true and isAutoIncremental is true, a new GUID will be generated automatically for new entities.
        /// When isAutoIncremental is false, you must manually set the primary key value before inserting.
        /// </remarks>
        public PrimaryKey(bool isAutoIncremental = true, bool isGUID = false)
        {
            IsAutoIncremental = isAutoIncremental;
            IsGUID = isGUID;
        }

        /// <summary>
        /// Gets or sets whether the primary key is auto-incremental
        /// </summary>
        /// <value>
        /// True if the primary key value is automatically generated by the database or ORM;
        /// false if the value must be manually set before insertion.
        /// </value>
        public bool IsAutoIncremental { get; set; } = true;

        /// <summary>
        /// Gets or sets whether the primary key is a GUID
        /// </summary>
        /// <value>
        /// True if the primary key is a GUID type that should be automatically generated;
        /// false for other data types like integers.
        /// </value>
        public bool IsGUID { get; set; } = false;
    }
}
